### ISSUE TITLE
Does Not Work Under Blender 2.65, 2.83, or 3.4.0

### ISSUE THREAD

**Issue by lorenzsandi** [poikilos/io_import_x#13]
Tried three different versions of Blender and none want to work with this addon when installed through the addon manager.

**Comment by Poikilos** [comment]
Currently it targets the **LTS ([long-term support](https://www.blender.org/download/lts/3-3/))** version. There are frequent major changes to the Blender API, and individuals making add-ons can only do so much. I am targeting LTS to provide the best support given the difficulty.

:edit: I worked on it in 3.3.x LTS but it also works in 3.6.0 LTS, so I'm not sure why you had trouble with 3.4.0. Explain exactly what occurred.
- Did you install the repo ZIP as explained in the readme?
- Did you enable the addon?
- Did you try importing something with "File", "Import", "DirectX (x)"?
- Note that this add-on doesn't work with binary X files, only ASCII X files (ones viewable in notepad as legible code rather than random characters).
- What was the error message (You can copy a screenshot to the clipboard using the PrtScr key on your keyboard then Ctrl+V to paste it into an issue or comment, or if you are using Linux or the Windows Snipping Tool, select the image from your screenshots folder such as Pictures)?

Older versions (below 3.3): I've listed older forks of the directX importer (not mine) that work in older versions of Blender at https://github.com/Poikilos/io_import_x/issues/5#issuecomment-1937021464

**Comment by KakekAFromNowherE** [comment]
You say it does but it wont install for me in the LTS 3.3.7 version. I try to enable it and it only gives me this message: 
![Screenshot_205](https://github.com/Poikilos/io_import_x/assets/69403065/31a11b06-06b9-476d-abeb-2394d1b55ee6)

**Comment by Poikilos** [comment]
@KakekAFromNowherE That sounds like it wasn't installed correctly. Try removing it then try the instructions in (my forked) readme. I am able to install it on 3.3.7.

**Comment by DanielMoravek** [comment]
It works well with **Blender 3.5.1**, I have downloaded it from that **"code"** button and **downloaded as a zip**, **not from Tag releases**

![AddonWorks](https://github.com/Poikilos/io_import_x/assets/39673731/f278c402-5247-4c31-ac3a-3ada0f65b24a)

**But im still on Win7, using BlenderCompat build.**

**Comment by KakekAFromNowherE** [comment]
Oh, that worked. thanks!

**Comment by Poikilos** [comment]
@lorenzsandi I can't test in every version of Blender, it is not practical. Please use versions I suggested and let me know if that works or answer the questions in my edited comment above, so I can determine whether this issue should be closed.

**Comment by lorenzsandi** [comment]
> @lorenzsandi I can't test in every version of Blender, it is not practical. Please use versions I suggested and let me know if that works or answer the questions in my edited comment above, so I can determine whether this issue should be closed.

It's fine, close it. Thought this closed long ago lol
