### ISSUE TITLE
2,79b is not work with io_import_x help

### ISSUE THREAD

**Issue by CheeseRindo** [poikilos/io_import_x#16]
![image](https://github.com/Poikilos/io_import_x/assets/85827445/e9f45065-4632-4e2e-b8bf-e83f13e38e0c)

**Comment by Poikilos** [comment]
Properties are not available in an earlier version of Python. My fork will only work with later versions of Blender with later versions of Python, and that is the purpose of my fork. See here and please search existing issues before adding issues: https://github.com/Poikilos/io_import_x/issues/5

The original author's version rather than this fork should be tried with older versions of Blender.
