### ISSUE TITLE
Can't install addon for 2.79b?

### ISSUE THREAD

**Issue by flipdark95** [poikilos/io_import_x#5]
Hey there mate, I'm trying to install this addon for Blender 2.79b, but it won't show up in the addons list after I've installed the .rar file. Do I need to install the .py file instead?

I and a group of other modders are looking to use Blender to make animations for Project Zomboid, which uses the .X format for its models and animations. Definitely looking into trying to port the Plugin to 3.0 hopefully, but I have no clue how to do that.

**Comment by Poikilos** [comment]
Why try to use the add-on with 2.79 if you want it to work in 3.0? It already works in 2.92 and I will try making it compatible with 3.0. In either case, if you want to generate x files, you've come to the wrong place. This add-on only imports as much as possible (static non-animated) data from (ascii not binary) x files, so you can ween your project off of those nasty old proprietary files abandoned by Microsoft and save them as something else (after manually re-animating them). If the engine is limited to x format only, you have my condolences. [It isn't limited to x as of build 41--try using the FBX format](https://github.com/FWolfe/Zomboid-Modding-Guide) instead if requiring that Project Zomboid version works for you. 

If you want to generate x files you'll have to use an even older version of Blender that has x exporting, or you'll have to use a converter of some sort, but I don't know of any that work with animations. Otherwise, use something like the [unofficial repack of trueSpace](http://truespace3d.free.fr/index.php/truespace-7-6/) if that still has the feature. 

If I run Blender 2.79 from the Terminal and try to enable the add-on, I get:
```
Traceback (most recent call last):
  File "/home/owner/Downloads/blender-2.79b-linux-glibc219-x86_64/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/owner/.config/blender/2.79/scripts/addons/io_import_x-master/__init__.py", line 64
    files: CollectionProperty(type=bpy.types.PropertyGroup)
         ^
SyntaxError: invalid syntax
```

This code looks familiar. It is code added for compatibility with 2.8. The API changed so much in 2.8 that supporting 2.79 doesn't seem to be worth it anymore. As I said I'll work on the 3.0 compatibility soon.

**Comment by flipdark95** [comment]
Thank god it can handle FBX files. In any case, I was hoping to directly import .X files into Blender that still held their animation data, But if I can convert them first beforehand, that works for me.

Thanks for the help regardless :)

**Comment by Poikilos** [comment]
@davidpho90 Please use the original author's version or stujones11's fork if you must for some reason use an ultra-old version of Blender.
- Blender 2.6 but below 2.66: https://github.com/spamandeggs/directX_blender 
- Blender 2.66 or above but earlier than 2.79: https://github.com/stujones11/directX_blender
- Blender 2.79: https://github.com/limemidolin/directX_blender
- Blender 2.93 & possibly similar versions: https://gitlab.com/ldo/blender-addons-orphaned
